package net.minecraft.server;

import com.google.common.collect.Maps;
import com.google.common.collect.Sets;
import java.util.Iterator;
import java.util.Map;
import java.util.Set;
import java.util.function.BiConsumer;
import java.util.function.Consumer;

public class DebugReportLootEntity implements Consumer<BiConsumer<MinecraftKey, LootTable.a>> {

    private static final CriterionConditionEntity.a a = CriterionConditionEntity.a.a().a(CriterionConditionEntityFlags.a.a().a(true).b());
    private final Map<MinecraftKey, LootTable.a> b = Maps.newHashMap();

    public DebugReportLootEntity() {}

    private static LootTable.a a(IMaterial imaterial) {
        return LootTable.b().a(LootSelector.a().a((LootValue) LootValueConstant.a(1)).a((LootEntryAbstract.a) LootItem.a(imaterial))).a(LootSelector.a().a((LootValue) LootValueConstant.a(1)).a((LootEntryAbstract.a) LootSelectorLootTable.a(EntityTypes.SHEEP.g())));
    }

    public void accept(BiConsumer<MinecraftKey, LootTable.a> biconsumer) {
        this.a(EntityTypes.ARMOR_STAND, LootTable.b());
        this.a(EntityTypes.BAT, LootTable.b());
        this.a(EntityTypes.BLAZE, LootTable.b().a(LootSelector.a().a((LootValue) LootValueConstant.a(1)).a((LootEntryAbstract.a) LootItem.a((IMaterial) Items.BLAZE_ROD).b((LootItemFunction.a) LootItemFunctionSetCount.a((LootValue) LootValueBounds.a(0.0F, 1.0F))).b((LootItemFunction.a) LootEnchantFunction.a(LootValueBounds.a(0.0F, 1.0F)))).b(LootItemConditionKilledByPlayer.b())));
        this.a(EntityTypes.CAT, LootTable.b().a(LootSelector.a().a((LootValue) LootValueConstant.a(1)).a((LootEntryAbstract.a) LootItem.a((IMaterial) Items.STRING).b((LootItemFunction.a) LootItemFunctionSetCount.a((LootValue) LootValueBounds.a(0.0F, 2.0F))))));
        this.a(EntityTypes.CAVE_SPIDER, LootTable.b().a(LootSelector.a().a((LootValue) LootValueConstant.a(1)).a((LootEntryAbstract.a) LootItem.a((IMaterial) Items.STRING).b((LootItemFunction.a) LootItemFunctionSetCount.a((LootValue) LootValueBounds.a(0.0F, 2.0F))).b((LootItemFunction.a) LootEnchantFunction.a(LootValueBounds.a(0.0F, 1.0F))))).a(LootSelector.a().a((LootValue) LootValueConstant.a(1)).a((LootEntryAbstract.a) LootItem.a((IMaterial) Items.SPIDER_EYE).b((LootItemFunction.a) LootItemFunctionSetCount.a((LootValue) LootValueBounds.a(-1.0F, 1.0F))).b((LootItemFunction.a) LootEnchantFunction.a(LootValueBounds.a(0.0F, 1.0F)))).b(LootItemConditionKilledByPlayer.b())));
        this.a(EntityTypes.CHICKEN, LootTable.b().a(LootSelector.a().a((LootValue) LootValueConstant.a(1)).a((LootEntryAbstract.a) LootItem.a((IMaterial) Items.FEATHER).b((LootItemFunction.a) LootItemFunctionSetCount.a((LootValue) LootValueBounds.a(0.0F, 2.0F))).b((LootItemFunction.a) LootEnchantFunction.a(LootValueBounds.a(0.0F, 1.0F))))).a(LootSelector.a().a((LootValue) LootValueConstant.a(1)).a((LootEntryAbstract.a) LootItem.a((IMaterial) Items.CHICKEN).b((LootItemFunction.a) LootItemFunctionSmelt.b().b(LootItemConditionEntityProperty.a(LootTableInfo.EntityTarget.THIS, DebugReportLootEntity.a))).b((LootItemFunction.a) LootEnchantFunction.a(LootValueBounds.a(0.0F, 1.0F))))));
        this.a(EntityTypes.COD, LootTable.b().a(LootSelector.a().a((LootValue) LootValueConstant.a(1)).a((LootEntryAbstract.a) LootItem.a((IMaterial) Items.COD).b((LootItemFunction.a) LootItemFunctionSmelt.b().b(LootItemConditionEntityProperty.a(LootTableInfo.EntityTarget.THIS, DebugReportLootEntity.a))))).a(LootSelector.a().a((LootValue) LootValueConstant.a(1)).a((LootEntryAbstract.a) LootItem.a((IMaterial) Items.BONE_MEAL)).b(LootItemConditionRandomChance.a(0.05F))));
        this.a(EntityTypes.COW, LootTable.b().a(LootSelector.a().a((LootValue) LootValueConstant.a(1)).a((LootEntryAbstract.a) LootItem.a((IMaterial) Items.LEATHER).b((LootItemFunction.a) LootItemFunctionSetCount.a((LootValue) LootValueBounds.a(0.0F, 2.0F))).b((LootItemFunction.a) LootEnchantFunction.a(LootValueBounds.a(0.0F, 1.0F))))).a(LootSelector.a().a((LootValue) LootValueConstant.a(1)).a((LootEntryAbstract.a) LootItem.a((IMaterial) Items.BEEF).b((LootItemFunction.a) LootItemFunctionSetCount.a((LootValue) LootValueBounds.a(1.0F, 3.0F))).b((LootItemFunction.a) LootItemFunctionSmelt.b().b(LootItemConditionEntityProperty.a(LootTableInfo.EntityTarget.THIS, DebugReportLootEntity.a))).b((LootItemFunction.a) LootEnchantFunction.a(LootValueBounds.a(0.0F, 1.0F))))));
        this.a(EntityTypes.CREEPER, LootTable.b().a(LootSelector.a().a((LootValue) LootValueConstant.a(1)).a((LootEntryAbstract.a) LootItem.a((IMaterial) Items.GUNPOWDER).b((LootItemFunction.a) LootItemFunctionSetCount.a((LootValue) LootValueBounds.a(0.0F, 2.0F))).b((LootItemFunction.a) LootEnchantFunction.a(LootValueBounds.a(0.0F, 1.0F))))).a(LootSelector.a().a((LootEntryAbstract.a) LootSelectorTag.b(TagsItem.MUSIC_DISCS)).b(LootItemConditionEntityProperty.a(LootTableInfo.EntityTarget.KILLER, CriterionConditionEntity.a.a().a(TagsEntity.SKELETONS)))));
        this.a(EntityTypes.DOLPHIN, LootTable.b().a(LootSelector.a().a((LootValue) LootValueConstant.a(1)).a((LootEntryAbstract.a) LootItem.a((IMaterial) Items.COD).b((LootItemFunction.a) LootItemFunctionSetCount.a((LootValue) LootValueBounds.a(0.0F, 1.0F))).b((LootItemFunction.a) LootEnchantFunction.a(LootValueBounds.a(0.0F, 1.0F))).b((LootItemFunction.a) LootItemFunctionSmelt.b().b(LootItemConditionEntityProperty.a(LootTableInfo.EntityTarget.THIS, DebugReportLootEntity.a))))));
        this.a(EntityTypes.DONKEY, LootTable.b().a(LootSelector.a().a((LootValue) LootValueConstant.a(1)).a((LootEntryAbstract.a) LootItem.a((IMaterial) Items.LEATHER).b((LootItemFunction.a) LootItemFunctionSetCount.a((LootValue) LootValueBounds.a(0.0F, 2.0F))).b((LootItemFunction.a) LootEnchantFunction.a(LootValueBounds.a(0.0F, 1.0F))))));
        this.a(EntityTypes.DROWNED, LootTable.b().a(LootSelector.a().a((LootValue) LootValueConstant.a(1)).a((LootEntryAbstract.a) LootItem.a((IMaterial) Items.ROTTEN_FLESH).b((LootItemFunction.a) LootItemFunctionSetCount.a((LootValue) LootValueBounds.a(0.0F, 2.0F))).b((LootItemFunction.a) LootEnchantFunction.a(LootValueBounds.a(0.0F, 1.0F))))).a(LootSelector.a().a((LootValue) LootValueConstant.a(1)).a((LootEntryAbstract.a) LootItem.a((IMaterial) Items.GOLD_INGOT)).b(LootItemConditionKilledByPlayer.b()).b(LootItemConditionRandomChanceWithLooting.a(0.05F, 0.01F))));
        this.a(EntityTypes.ELDER_GUARDIAN, LootTable.b().a(LootSelector.a().a((LootValue) LootValueConstant.a(1)).a((LootEntryAbstract.a) LootItem.a((IMaterial) Items.PRISMARINE_SHARD).b((LootItemFunction.a) LootItemFunctionSetCount.a((LootValue) LootValueBounds.a(0.0F, 2.0F))).b((LootItemFunction.a) LootEnchantFunction.a(LootValueBounds.a(0.0F, 1.0F))))).a(LootSelector.a().a((LootValue) LootValueConstant.a(1)).a((LootEntryAbstract.a) LootItem.a((IMaterial) Items.COD).a(3).b((LootItemFunction.a) LootEnchantFunction.a(LootValueBounds.a(0.0F, 1.0F))).b((LootItemFunction.a) LootItemFunctionSmelt.b().b(LootItemConditionEntityProperty.a(LootTableInfo.EntityTarget.THIS, DebugReportLootEntity.a)))).a((LootEntryAbstract.a) LootItem.a((IMaterial) Items.PRISMARINE_CRYSTALS).a(2).b((LootItemFunction.a) LootEnchantFunction.a(LootValueBounds.a(0.0F, 1.0F)))).a((LootEntryAbstract.a) LootSelectorEmpty.a())).a(LootSelector.a().a((LootValue) LootValueConstant.a(1)).a((LootEntryAbstract.a) LootItem.a((IMaterial) Blocks.WET_SPONGE)).b(LootItemConditionKilledByPlayer.b())).a(LootSelector.a().a((LootValue) LootValueConstant.a(1)).a((LootEntryAbstract.a) LootSelectorLootTable.a(LootTables.ae)).b(LootItemConditionKilledByPlayer.b()).b(LootItemConditionRandomChanceWithLooting.a(0.025F, 0.01F))));
        this.a(EntityTypes.ENDER_DRAGON, LootTable.b());
        this.a(EntityTypes.ENDERMAN, LootTable.b().a(LootSelector.a().a((LootValue) LootValueConstant.a(1)).a((LootEntryAbstract.a) LootItem.a((IMaterial) Items.ENDER_PEARL).b((LootItemFunction.a) LootItemFunctionSetCount.a((LootValue) LootValueBounds.a(0.0F, 1.0F))).b((LootItemFunction.a) LootEnchantFunction.a(LootValueBounds.a(0.0F, 1.0F))))));
        this.a(EntityTypes.ENDERMITE, LootTable.b());
        this.a(EntityTypes.EVOKER, LootTable.b().a(LootSelector.a().a((LootValue) LootValueConstant.a(1)).a((LootEntryAbstract.a) LootItem.a((IMaterial) Items.TOTEM_OF_UNDYING))).a(LootSelector.a().a((LootValue) LootValueConstant.a(1)).a((LootEntryAbstract.a) LootItem.a((IMaterial) Items.EMERALD).b((LootItemFunction.a) LootItemFunctionSetCount.a((LootValue) LootValueBounds.a(0.0F, 1.0F))).b((LootItemFunction.a) LootEnchantFunction.a(LootValueBounds.a(0.0F, 1.0F)))).b(LootItemConditionKilledByPlayer.b())));
        this.a(EntityTypes.FOX, LootTable.b());
        this.a(EntityTypes.GHAST, LootTable.b().a(LootSelector.a().a((LootValue) LootValueConstant.a(1)).a((LootEntryAbstract.a) LootItem.a((IMaterial) Items.GHAST_TEAR).b((LootItemFunction.a) LootItemFunctionSetCount.a((LootValue) LootValueBounds.a(0.0F, 1.0F))).b((LootItemFunction.a) LootEnchantFunction.a(LootValueBounds.a(0.0F, 1.0F))))).a(LootSelector.a().a((LootValue) LootValueConstant.a(1)).a((LootEntryAbstract.a) LootItem.a((IMaterial) Items.GUNPOWDER).b((LootItemFunction.a) LootItemFunctionSetCount.a((LootValue) LootValueBounds.a(0.0F, 2.0F))).b((LootItemFunction.a) LootEnchantFunction.a(LootValueBounds.a(0.0F, 1.0F))))));
        this.a(EntityTypes.GIANT, LootTable.b());
        this.a(EntityTypes.GUARDIAN, LootTable.b().a(LootSelector.a().a((LootValue) LootValueConstant.a(1)).a((LootEntryAbstract.a) LootItem.a((IMaterial) Items.PRISMARINE_SHARD).b((LootItemFunction.a) LootItemFunctionSetCount.a((LootValue) LootValueBounds.a(0.0F, 2.0F))).b((LootItemFunction.a) LootEnchantFunction.a(LootValueBounds.a(0.0F, 1.0F))))).a(LootSelector.a().a((LootValue) LootValueConstant.a(1)).a((LootEntryAbstract.a) LootItem.a((IMaterial) Items.COD).a(2).b((LootItemFunction.a) LootEnchantFunction.a(LootValueBounds.a(0.0F, 1.0F))).b((LootItemFunction.a) LootItemFunctionSmelt.b().b(LootItemConditionEntityProperty.a(LootTableInfo.EntityTarget.THIS, DebugReportLootEntity.a)))).a((LootEntryAbstract.a) LootItem.a((IMaterial) Items.PRISMARINE_CRYSTALS).a(2).b((LootItemFunction.a) LootEnchantFunction.a(LootValueBounds.a(0.0F, 1.0F)))).a((LootEntryAbstract.a) LootSelectorEmpty.a())).a(LootSelector.a().a((LootValue) LootValueConstant.a(1)).a((LootEntryAbstract.a) LootSelectorLootTable.a(LootTables.ae)).b(LootItemConditionKilledByPlayer.b()).b(LootItemConditionRandomChanceWithLooting.a(0.025F, 0.01F))));
        this.a(EntityTypes.HORSE, LootTable.b().a(LootSelector.a().a((LootValue) LootValueConstant.a(1)).a((LootEntryAbstract.a) LootItem.a((IMaterial) Items.LEATHER).b((LootItemFunction.a) LootItemFunctionSetCount.a((LootValue) LootValueBounds.a(0.0F, 2.0F))).b((LootItemFunction.a) LootEnchantFunction.a(LootValueBounds.a(0.0F, 1.0F))))));
        this.a(EntityTypes.HUSK, LootTable.b().a(LootSelector.a().a((LootValue) LootValueConstant.a(1)).a((LootEntryAbstract.a) LootItem.a((IMaterial) Items.ROTTEN_FLESH).b((LootItemFunction.a) LootItemFunctionSetCount.a((LootValue) LootValueBounds.a(0.0F, 2.0F))).b((LootItemFunction.a) LootEnchantFunction.a(LootValueBounds.a(0.0F, 1.0F))))).a(LootSelector.a().a((LootValue) LootValueConstant.a(1)).a((LootEntryAbstract.a) LootItem.a((IMaterial) Items.IRON_INGOT)).a((LootEntryAbstract.a) LootItem.a((IMaterial) Items.CARROT)).a((LootEntryAbstract.a) LootItem.a((IMaterial) Items.POTATO)).b(LootItemConditionKilledByPlayer.b()).b(LootItemConditionRandomChanceWithLooting.a(0.025F, 0.01F))));
        this.a(EntityTypes.RAVAGER, LootTable.b().a(LootSelector.a().a((LootValue) LootValueConstant.a(1)).a((LootEntryAbstract.a) LootItem.a((IMaterial) Items.SADDLE).b((LootItemFunction.a) LootItemFunctionSetCount.a((LootValue) LootValueConstant.a(1))))));
        this.a(EntityTypes.ILLUSIONER, LootTable.b());
        this.a(EntityTypes.IRON_GOLEM, LootTable.b().a(LootSelector.a().a((LootValue) LootValueConstant.a(1)).a((LootEntryAbstract.a) LootItem.a((IMaterial) Blocks.POPPY).b((LootItemFunction.a) LootItemFunctionSetCount.a((LootValue) LootValueBounds.a(0.0F, 2.0F))))).a(LootSelector.a().a((LootValue) LootValueConstant.a(1)).a((LootEntryAbstract.a) LootItem.a((IMaterial) Items.IRON_INGOT).b((LootItemFunction.a) LootItemFunctionSetCount.a((LootValue) LootValueBounds.a(3.0F, 5.0F))))));
        this.a(EntityTypes.LLAMA, LootTable.b().a(LootSelector.a().a((LootValue) LootValueConstant.a(1)).a((LootEntryAbstract.a) LootItem.a((IMaterial) Items.LEATHER).b((LootItemFunction.a) LootItemFunctionSetCount.a((LootValue) LootValueBounds.a(0.0F, 2.0F))).b((LootItemFunction.a) LootEnchantFunction.a(LootValueBounds.a(0.0F, 1.0F))))));
        this.a(EntityTypes.MAGMA_CUBE, LootTable.b().a(LootSelector.a().a((LootValue) LootValueConstant.a(1)).a((LootEntryAbstract.a) LootItem.a((IMaterial) Items.MAGMA_CREAM).b((LootItemFunction.a) LootItemFunctionSetCount.a((LootValue) LootValueBounds.a(-2.0F, 1.0F))).b((LootItemFunction.a) LootEnchantFunction.a(LootValueBounds.a(0.0F, 1.0F))))));
        this.a(EntityTypes.MULE, LootTable.b().a(LootSelector.a().a((LootValue) LootValueConstant.a(1)).a((LootEntryAbstract.a) LootItem.a((IMaterial) Items.LEATHER).b((LootItemFunction.a) LootItemFunctionSetCount.a((LootValue) LootValueBounds.a(0.0F, 2.0F))).b((LootItemFunction.a) LootEnchantFunction.a(LootValueBounds.a(0.0F, 1.0F))))));
        this.a(EntityTypes.MOOSHROOM, LootTable.b().a(LootSelector.a().a((LootValue) LootValueConstant.a(1)).a((LootEntryAbstract.a) LootItem.a((IMaterial) Items.LEATHER).b((LootItemFunction.a) LootItemFunctionSetCount.a((LootValue) LootValueBounds.a(0.0F, 2.0F))).b((LootItemFunction.a) LootEnchantFunction.a(LootValueBounds.a(0.0F, 1.0F))))).a(LootSelector.a().a((LootValue) LootValueConstant.a(1)).a((LootEntryAbstract.a) LootItem.a((IMaterial) Items.BEEF).b((LootItemFunction.a) LootItemFunctionSetCount.a((LootValue) LootValueBounds.a(1.0F, 3.0F))).b((LootItemFunction.a) LootItemFunctionSmelt.b().b(LootItemConditionEntityProperty.a(LootTableInfo.EntityTarget.THIS, DebugReportLootEntity.a))).b((LootItemFunction.a) LootEnchantFunction.a(LootValueBounds.a(0.0F, 1.0F))))));
        this.a(EntityTypes.OCELOT, LootTable.b());
        this.a(EntityTypes.PANDA, LootTable.b().a(LootSelector.a().a((LootValue) LootValueConstant.a(1)).a((LootEntryAbstract.a) LootItem.a((IMaterial) Blocks.BAMBOO).b((LootItemFunction.a) LootItemFunctionSetCount.a((LootValue) LootValueConstant.a(1))))));
        this.a(EntityTypes.PARROT, LootTable.b().a(LootSelector.a().a((LootValue) LootValueConstant.a(1)).a((LootEntryAbstract.a) LootItem.a((IMaterial) Items.FEATHER).b((LootItemFunction.a) LootItemFunctionSetCount.a((LootValue) LootValueBounds.a(1.0F, 2.0F))).b((LootItemFunction.a) LootEnchantFunction.a(LootValueBounds.a(0.0F, 1.0F))))));
        this.a(EntityTypes.PHANTOM, LootTable.b().a(LootSelector.a().a((LootValue) LootValueConstant.a(1)).a((LootEntryAbstract.a) LootItem.a((IMaterial) Items.PHANTOM_MEMBRANE).b((LootItemFunction.a) LootItemFunctionSetCount.a((LootValue) LootValueBounds.a(0.0F, 1.0F))).b((LootItemFunction.a) LootEnchantFunction.a(LootValueBounds.a(0.0F, 1.0F)))).b(LootItemConditionKilledByPlayer.b())));
        this.a(EntityTypes.PIG, LootTable.b().a(LootSelector.a().a((LootValue) LootValueConstant.a(1)).a((LootEntryAbstract.a) LootItem.a((IMaterial) Items.PORKCHOP).b((LootItemFunction.a) LootItemFunctionSetCount.a((LootValue) LootValueBounds.a(1.0F, 3.0F))).b((LootItemFunction.a) LootItemFunctionSmelt.b().b(LootItemConditionEntityProperty.a(LootTableInfo.EntityTarget.THIS, DebugReportLootEntity.a))).b((LootItemFunction.a) LootEnchantFunction.a(LootValueBounds.a(0.0F, 1.0F))))));
        this.a(EntityTypes.PILLAGER, LootTable.b());
        this.a(EntityTypes.PLAYER, LootTable.b());
        this.a(EntityTypes.POLAR_BEAR, LootTable.b().a(LootSelector.a().a((LootValue) LootValueConstant.a(1)).a((LootEntryAbstract.a) LootItem.a((IMaterial) Items.COD).a(3).b((LootItemFunction.a) LootItemFunctionSetCount.a((LootValue) LootValueBounds.a(0.0F, 2.0F))).b((LootItemFunction.a) LootEnchantFunction.a(LootValueBounds.a(0.0F, 1.0F)))).a((LootEntryAbstract.a) LootItem.a((IMaterial) Items.SALMON).b((LootItemFunction.a) LootItemFunctionSetCount.a((LootValue) LootValueBounds.a(0.0F, 2.0F))).b((LootItemFunction.a) LootEnchantFunction.a(LootValueBounds.a(0.0F, 1.0F))))));
        this.a(EntityTypes.PUFFERFISH, LootTable.b().a(LootSelector.a().a((LootValue) LootValueConstant.a(1)).a((LootEntryAbstract.a) LootItem.a((IMaterial) Items.PUFFERFISH).b((LootItemFunction.a) LootItemFunctionSetCount.a((LootValue) LootValueConstant.a(1))))).a(LootSelector.a().a((LootValue) LootValueConstant.a(1)).a((LootEntryAbstract.a) LootItem.a((IMaterial) Items.BONE_MEAL)).b(LootItemConditionRandomChance.a(0.05F))));
        this.a(EntityTypes.RABBIT, LootTable.b().a(LootSelector.a().a((LootValue) LootValueConstant.a(1)).a((LootEntryAbstract.a) LootItem.a((IMaterial) Items.RABBIT_HIDE).b((LootItemFunction.a) LootItemFunctionSetCount.a((LootValue) LootValueBounds.a(0.0F, 1.0F))).b((LootItemFunction.a) LootEnchantFunction.a(LootValueBounds.a(0.0F, 1.0F))))).a(LootSelector.a().a((LootValue) LootValueConstant.a(1)).a((LootEntryAbstract.a) LootItem.a((IMaterial) Items.RABBIT).b((LootItemFunction.a) LootItemFunctionSetCount.a((LootValue) LootValueBounds.a(0.0F, 1.0F))).b((LootItemFunction.a) LootItemFunctionSmelt.b().b(LootItemConditionEntityProperty.a(LootTableInfo.EntityTarget.THIS, DebugReportLootEntity.a))).b((LootItemFunction.a) LootEnchantFunction.a(LootValueBounds.a(0.0F, 1.0F))))).a(LootSelector.a().a((LootValue) LootValueConstant.a(1)).a((LootEntryAbstract.a) LootItem.a((IMaterial) Items.RABBIT_FOOT)).b(LootItemConditionKilledByPlayer.b()).b(LootItemConditionRandomChanceWithLooting.a(0.1F, 0.03F))));
        this.a(EntityTypes.SALMON, LootTable.b().a(LootSelector.a().a((LootValue) LootValueConstant.a(1)).a((LootEntryAbstract.a) LootItem.a((IMaterial) Items.SALMON).b((LootItemFunction.a) LootItemFunctionSmelt.b().b(LootItemConditionEntityProperty.a(LootTableInfo.EntityTarget.THIS, DebugReportLootEntity.a))))).a(LootSelector.a().a((LootValue) LootValueConstant.a(1)).a((LootEntryAbstract.a) LootItem.a((IMaterial) Items.BONE_MEAL)).b(LootItemConditionRandomChance.a(0.05F))));
        this.a(EntityTypes.SHEEP, LootTable.b().a(LootSelector.a().a((LootValue) LootValueConstant.a(1)).a((LootEntryAbstract.a) LootItem.a((IMaterial) Items.MUTTON).b((LootItemFunction.a) LootItemFunctionSetCount.a((LootValue) LootValueBounds.a(1.0F, 2.0F))).b((LootItemFunction.a) LootItemFunctionSmelt.b().b(LootItemConditionEntityProperty.a(LootTableInfo.EntityTarget.THIS, DebugReportLootEntity.a))).b((LootItemFunction.a) LootEnchantFunction.a(LootValueBounds.a(0.0F, 1.0F))))));
        this.a(LootTables.aa, a((IMaterial) Blocks.BLACK_WOOL));
        this.a(LootTables.W, a((IMaterial) Blocks.BLUE_WOOL));
        this.a(LootTables.X, a((IMaterial) Blocks.BROWN_WOOL));
        this.a(LootTables.U, a((IMaterial) Blocks.CYAN_WOOL));
        this.a(LootTables.S, a((IMaterial) Blocks.GRAY_WOOL));
        this.a(LootTables.Y, a((IMaterial) Blocks.GREEN_WOOL));
        this.a(LootTables.O, a((IMaterial) Blocks.LIGHT_BLUE_WOOL));
        this.a(LootTables.T, a((IMaterial) Blocks.LIGHT_GRAY_WOOL));
        this.a(LootTables.Q, a((IMaterial) Blocks.LIME_WOOL));
        this.a(LootTables.N, a((IMaterial) Blocks.MAGENTA_WOOL));
        this.a(LootTables.M, a((IMaterial) Blocks.ORANGE_WOOL));
        this.a(LootTables.R, a((IMaterial) Blocks.PINK_WOOL));
        this.a(LootTables.V, a((IMaterial) Blocks.PURPLE_WOOL));
        this.a(LootTables.Z, a((IMaterial) Blocks.RED_WOOL));
        this.a(LootTables.L, a((IMaterial) Blocks.WHITE_WOOL));
        this.a(LootTables.P, a((IMaterial) Blocks.YELLOW_WOOL));
        this.a(EntityTypes.SHULKER, LootTable.b().a(LootSelector.a().a((LootValue) LootValueConstant.a(1)).a((LootEntryAbstract.a) LootItem.a((IMaterial) Items.SHULKER_SHELL)).b(LootItemConditionRandomChanceWithLooting.a(0.5F, 0.0625F))));
        this.a(EntityTypes.SILVERFISH, LootTable.b());
        this.a(EntityTypes.SKELETON, LootTable.b().a(LootSelector.a().a((LootValue) LootValueConstant.a(1)).a((LootEntryAbstract.a) LootItem.a((IMaterial) Items.ARROW).b((LootItemFunction.a) LootItemFunctionSetCount.a((LootValue) LootValueBounds.a(0.0F, 2.0F))).b((LootItemFunction.a) LootEnchantFunction.a(LootValueBounds.a(0.0F, 1.0F))))).a(LootSelector.a().a((LootValue) LootValueConstant.a(1)).a((LootEntryAbstract.a) LootItem.a((IMaterial) Items.BONE).b((LootItemFunction.a) LootItemFunctionSetCount.a((LootValue) LootValueBounds.a(0.0F, 2.0F))).b((LootItemFunction.a) LootEnchantFunction.a(LootValueBounds.a(0.0F, 1.0F))))));
        this.a(EntityTypes.SKELETON_HORSE, LootTable.b().a(LootSelector.a().a((LootValue) LootValueConstant.a(1)).a((LootEntryAbstract.a) LootItem.a((IMaterial) Items.BONE).b((LootItemFunction.a) LootItemFunctionSetCount.a((LootValue) LootValueBounds.a(0.0F, 2.0F))).b((LootItemFunction.a) LootEnchantFunction.a(LootValueBounds.a(0.0F, 1.0F))))));
        this.a(EntityTypes.SLIME, LootTable.b().a(LootSelector.a().a((LootValue) LootValueConstant.a(1)).a((LootEntryAbstract.a) LootItem.a((IMaterial) Items.SLIME_BALL).b((LootItemFunction.a) LootItemFunctionSetCount.a((LootValue) LootValueBounds.a(0.0F, 2.0F))).b((LootItemFunction.a) LootEnchantFunction.a(LootValueBounds.a(0.0F, 1.0F))))));
        this.a(EntityTypes.SNOW_GOLEM, LootTable.b().a(LootSelector.a().a((LootValue) LootValueConstant.a(1)).a((LootEntryAbstract.a) LootItem.a((IMaterial) Items.SNOWBALL).b((LootItemFunction.a) LootItemFunctionSetCount.a((LootValue) LootValueBounds.a(0.0F, 15.0F))))));
        this.a(EntityTypes.SPIDER, LootTable.b().a(LootSelector.a().a((LootValue) LootValueConstant.a(1)).a((LootEntryAbstract.a) LootItem.a((IMaterial) Items.STRING).b((LootItemFunction.a) LootItemFunctionSetCount.a((LootValue) LootValueBounds.a(0.0F, 2.0F))).b((LootItemFunction.a) LootEnchantFunction.a(LootValueBounds.a(0.0F, 1.0F))))).a(LootSelector.a().a((LootValue) LootValueConstant.a(1)).a((LootEntryAbstract.a) LootItem.a((IMaterial) Items.SPIDER_EYE).b((LootItemFunction.a) LootItemFunctionSetCount.a((LootValue) LootValueBounds.a(-1.0F, 1.0F))).b((LootItemFunction.a) LootEnchantFunction.a(LootValueBounds.a(0.0F, 1.0F)))).b(LootItemConditionKilledByPlayer.b())));
        this.a(EntityTypes.SQUID, LootTable.b().a(LootSelector.a().a((LootValue) LootValueConstant.a(1)).a((LootEntryAbstract.a) LootItem.a((IMaterial) Items.INK_SAC).b((LootItemFunction.a) LootItemFunctionSetCount.a((LootValue) LootValueBounds.a(1.0F, 3.0F))).b((LootItemFunction.a) LootEnchantFunction.a(LootValueBounds.a(0.0F, 1.0F))))));
        this.a(EntityTypes.STRAY, LootTable.b().a(LootSelector.a().a((LootValue) LootValueConstant.a(1)).a((LootEntryAbstract.a) LootItem.a((IMaterial) Items.ARROW).b((LootItemFunction.a) LootItemFunctionSetCount.a((LootValue) LootValueBounds.a(0.0F, 2.0F))).b((LootItemFunction.a) LootEnchantFunction.a(LootValueBounds.a(0.0F, 1.0F))))).a(LootSelector.a().a((LootValue) LootValueConstant.a(1)).a((LootEntryAbstract.a) LootItem.a((IMaterial) Items.BONE).b((LootItemFunction.a) LootItemFunctionSetCount.a((LootValue) LootValueBounds.a(0.0F, 2.0F))).b((LootItemFunction.a) LootEnchantFunction.a(LootValueBounds.a(0.0F, 1.0F))))).a(LootSelector.a().a((LootValue) LootValueConstant.a(1)).a((LootEntryAbstract.a) LootItem.a((IMaterial) Items.TIPPED_ARROW).b((LootItemFunction.a) LootItemFunctionSetCount.a((LootValue) LootValueBounds.a(0.0F, 1.0F))).b((LootItemFunction.a) LootEnchantFunction.a(LootValueBounds.a(0.0F, 1.0F)).a(1)).b((LootItemFunction.a) LootItemFunctionSetTag.a((NBTTagCompound) SystemUtils.a((Object) (new NBTTagCompound()), (nbttagcompound) -> {
            nbttagcompound.setString("Potion", "minecraft:slowness");
        })))).b(LootItemConditionKilledByPlayer.b())));
        this.a(EntityTypes.TRADER_LLAMA, LootTable.b().a(LootSelector.a().a((LootValue) LootValueConstant.a(1)).a((LootEntryAbstract.a) LootItem.a((IMaterial) Items.LEATHER).b((LootItemFunction.a) LootItemFunctionSetCount.a((LootValue) LootValueBounds.a(0.0F, 2.0F))).b((LootItemFunction.a) LootEnchantFunction.a(LootValueBounds.a(0.0F, 1.0F))))));
        this.a(EntityTypes.TROPICAL_FISH, LootTable.b().a(LootSelector.a().a((LootValue) LootValueConstant.a(1)).a((LootEntryAbstract.a) LootItem.a((IMaterial) Items.TROPICAL_FISH).b((LootItemFunction.a) LootItemFunctionSetCount.a((LootValue) LootValueConstant.a(1))))).a(LootSelector.a().a((LootValue) LootValueConstant.a(1)).a((LootEntryAbstract.a) LootItem.a((IMaterial) Items.BONE_MEAL)).b(LootItemConditionRandomChance.a(0.05F))));
        this.a(EntityTypes.TURTLE, LootTable.b().a(LootSelector.a().a((LootValue) LootValueConstant.a(1)).a((LootEntryAbstract.a) LootItem.a((IMaterial) Blocks.SEAGRASS).a(3).b((LootItemFunction.a) LootItemFunctionSetCount.a((LootValue) LootValueBounds.a(0.0F, 2.0F))).b((LootItemFunction.a) LootEnchantFunction.a(LootValueBounds.a(0.0F, 1.0F))))).a(LootSelector.a().a((LootValue) LootValueConstant.a(1)).a((LootEntryAbstract.a) LootItem.a((IMaterial) Items.BOWL)).b(LootItemConditionDamageSourceProperties.a(CriterionConditionDamageSource.a.a().h(true)))));
        this.a(EntityTypes.VEX, LootTable.b());
        this.a(EntityTypes.VILLAGER, LootTable.b());
        this.a(EntityTypes.WANDERING_TRADER, LootTable.b());
        this.a(EntityTypes.VINDICATOR, LootTable.b().a(LootSelector.a().a((LootValue) LootValueConstant.a(1)).a((LootEntryAbstract.a) LootItem.a((IMaterial) Items.EMERALD).b((LootItemFunction.a) LootItemFunctionSetCount.a((LootValue) LootValueBounds.a(0.0F, 1.0F))).b((LootItemFunction.a) LootEnchantFunction.a(LootValueBounds.a(0.0F, 1.0F)))).b(LootItemConditionKilledByPlayer.b())));
        this.a(EntityTypes.WITCH, LootTable.b().a(LootSelector.a().a((LootValue) LootValueBounds.a(1.0F, 3.0F)).a((LootEntryAbstract.a) LootItem.a((IMaterial) Items.GLOWSTONE_DUST).b((LootItemFunction.a) LootItemFunctionSetCount.a((LootValue) LootValueBounds.a(0.0F, 2.0F))).b((LootItemFunction.a) LootEnchantFunction.a(LootValueBounds.a(0.0F, 1.0F)))).a((LootEntryAbstract.a) LootItem.a((IMaterial) Items.SUGAR).b((LootItemFunction.a) LootItemFunctionSetCount.a((LootValue) LootValueBounds.a(0.0F, 2.0F))).b((LootItemFunction.a) LootEnchantFunction.a(LootValueBounds.a(0.0F, 1.0F)))).a((LootEntryAbstract.a) LootItem.a((IMaterial) Items.REDSTONE).b((LootItemFunction.a) LootItemFunctionSetCount.a((LootValue) LootValueBounds.a(0.0F, 2.0F))).b((LootItemFunction.a) LootEnchantFunction.a(LootValueBounds.a(0.0F, 1.0F)))).a((LootEntryAbstract.a) LootItem.a((IMaterial) Items.SPIDER_EYE).b((LootItemFunction.a) LootItemFunctionSetCount.a((LootValue) LootValueBounds.a(0.0F, 2.0F))).b((LootItemFunction.a) LootEnchantFunction.a(LootValueBounds.a(0.0F, 1.0F)))).a((LootEntryAbstract.a) LootItem.a((IMaterial) Items.GLASS_BOTTLE).b((LootItemFunction.a) LootItemFunctionSetCount.a((LootValue) LootValueBounds.a(0.0F, 2.0F))).b((LootItemFunction.a) LootEnchantFunction.a(LootValueBounds.a(0.0F, 1.0F)))).a((LootEntryAbstract.a) LootItem.a((IMaterial) Items.GUNPOWDER).b((LootItemFunction.a) LootItemFunctionSetCount.a((LootValue) LootValueBounds.a(0.0F, 2.0F))).b((LootItemFunction.a) LootEnchantFunction.a(LootValueBounds.a(0.0F, 1.0F)))).a((LootEntryAbstract.a) LootItem.a((IMaterial) Items.STICK).a(2).b((LootItemFunction.a) LootItemFunctionSetCount.a((LootValue) LootValueBounds.a(0.0F, 2.0F))).b((LootItemFunction.a) LootEnchantFunction.a(LootValueBounds.a(0.0F, 1.0F))))));
        this.a(EntityTypes.WITHER, LootTable.b());
        this.a(EntityTypes.WITHER_SKELETON, LootTable.b().a(LootSelector.a().a((LootValue) LootValueConstant.a(1)).a((LootEntryAbstract.a) LootItem.a((IMaterial) Items.COAL).b((LootItemFunction.a) LootItemFunctionSetCount.a((LootValue) LootValueBounds.a(-1.0F, 1.0F))).b((LootItemFunction.a) LootEnchantFunction.a(LootValueBounds.a(0.0F, 1.0F))))).a(LootSelector.a().a((LootValue) LootValueConstant.a(1)).a((LootEntryAbstract.a) LootItem.a((IMaterial) Items.BONE).b((LootItemFunction.a) LootItemFunctionSetCount.a((LootValue) LootValueBounds.a(0.0F, 2.0F))).b((LootItemFunction.a) LootEnchantFunction.a(LootValueBounds.a(0.0F, 1.0F))))).a(LootSelector.a().a((LootValue) LootValueConstant.a(1)).a((LootEntryAbstract.a) LootItem.a((IMaterial) Blocks.WITHER_SKELETON_SKULL)).b(LootItemConditionKilledByPlayer.b()).b(LootItemConditionRandomChanceWithLooting.a(0.025F, 0.01F))));
        this.a(EntityTypes.WOLF, LootTable.b());
        this.a(EntityTypes.ZOMBIE, LootTable.b().a(LootSelector.a().a((LootValue) LootValueConstant.a(1)).a((LootEntryAbstract.a) LootItem.a((IMaterial) Items.ROTTEN_FLESH).b((LootItemFunction.a) LootItemFunctionSetCount.a((LootValue) LootValueBounds.a(0.0F, 2.0F))).b((LootItemFunction.a) LootEnchantFunction.a(LootValueBounds.a(0.0F, 1.0F))))).a(LootSelector.a().a((LootValue) LootValueConstant.a(1)).a((LootEntryAbstract.a) LootItem.a((IMaterial) Items.IRON_INGOT)).a((LootEntryAbstract.a) LootItem.a((IMaterial) Items.CARROT)).a((LootEntryAbstract.a) LootItem.a((IMaterial) Items.POTATO)).b(LootItemConditionKilledByPlayer.b()).b(LootItemConditionRandomChanceWithLooting.a(0.025F, 0.01F))));
        this.a(EntityTypes.ZOMBIE_HORSE, LootTable.b().a(LootSelector.a().a((LootValue) LootValueConstant.a(1)).a((LootEntryAbstract.a) LootItem.a((IMaterial) Items.ROTTEN_FLESH).b((LootItemFunction.a) LootItemFunctionSetCount.a((LootValue) LootValueBounds.a(0.0F, 2.0F))).b((LootItemFunction.a) LootEnchantFunction.a(LootValueBounds.a(0.0F, 1.0F))))));
        this.a(EntityTypes.ZOMBIE_PIGMAN, LootTable.b().a(LootSelector.a().a((LootValue) LootValueConstant.a(1)).a((LootEntryAbstract.a) LootItem.a((IMaterial) Items.ROTTEN_FLESH).b((LootItemFunction.a) LootItemFunctionSetCount.a((LootValue) LootValueBounds.a(0.0F, 1.0F))).b((LootItemFunction.a) LootEnchantFunction.a(LootValueBounds.a(0.0F, 1.0F))))).a(LootSelector.a().a((LootValue) LootValueConstant.a(1)).a((LootEntryAbstract.a) LootItem.a((IMaterial) Items.GOLD_NUGGET).b((LootItemFunction.a) LootItemFunctionSetCount.a((LootValue) LootValueBounds.a(0.0F, 1.0F))).b((LootItemFunction.a) LootEnchantFunction.a(LootValueBounds.a(0.0F, 1.0F))))).a(LootSelector.a().a((LootValue) LootValueConstant.a(1)).a((LootEntryAbstract.a) LootItem.a((IMaterial) Items.GOLD_INGOT)).b(LootItemConditionKilledByPlayer.b()).b(LootItemConditionRandomChanceWithLooting.a(0.025F, 0.01F))));
        this.a(EntityTypes.ZOMBIE_VILLAGER, LootTable.b().a(LootSelector.a().a((LootValue) LootValueConstant.a(1)).a((LootEntryAbstract.a) LootItem.a((IMaterial) Items.ROTTEN_FLESH).b((LootItemFunction.a) LootItemFunctionSetCount.a((LootValue) LootValueBounds.a(0.0F, 2.0F))).b((LootItemFunction.a) LootEnchantFunction.a(LootValueBounds.a(0.0F, 1.0F))))).a(LootSelector.a().a((LootValue) LootValueConstant.a(1)).a((LootEntryAbstract.a) LootItem.a((IMaterial) Items.IRON_INGOT)).a((LootEntryAbstract.a) LootItem.a((IMaterial) Items.CARROT)).a((LootEntryAbstract.a) LootItem.a((IMaterial) Items.POTATO)).b(LootItemConditionKilledByPlayer.b()).b(LootItemConditionRandomChanceWithLooting.a(0.025F, 0.01F))));
        Set<MinecraftKey> set = Sets.newHashSet();
        Iterator iterator = IRegistry.ENTITY_TYPE.iterator();

        while (iterator.hasNext()) {
            EntityTypes<?> entitytypes = (EntityTypes) iterator.next();
            MinecraftKey minecraftkey = entitytypes.g();

            if (entitytypes != EntityTypes.PLAYER && entitytypes != EntityTypes.ARMOR_STAND && entitytypes.d() == EnumCreatureType.MISC) {
                if (minecraftkey != LootTables.a && this.b.remove(minecraftkey) != null) {
                    throw new IllegalStateException(String.format("Weird loottable '%s' for '%s', not a LivingEntity so should not have loot", minecraftkey, IRegistry.ENTITY_TYPE.getKey(entitytypes)));
                }
            } else if (minecraftkey != LootTables.a && set.add(minecraftkey)) {
                LootTable.a loottable_a = (LootTable.a) this.b.remove(minecraftkey);

                if (loottable_a == null) {
                    throw new IllegalStateException(String.format("Missing loottable '%s' for '%s'", minecraftkey, IRegistry.ENTITY_TYPE.getKey(entitytypes)));
                }

                biconsumer.accept(minecraftkey, loottable_a);
            }
        }

        this.b.forEach(biconsumer::accept);
    }

    private void a(EntityTypes<?> entitytypes, LootTable.a loottable_a) {
        this.a(entitytypes.g(), loottable_a);
    }

    private void a(MinecraftKey minecraftkey, LootTable.a loottable_a) {
        this.b.put(minecraftkey, loottable_a);
    }
}
